### ISSUE TITLE
Suggestion: build-port

### ISSUE THREAD

**Issue by peter1000** [NuTyX/xfce4#6]
just thought that it might be good to clarify what the option does:

e.g.: https://github.com/NuTyX/xfce4/blob/master/scripts/build-port#L44

```
	echo "   -l,   --list                will list all the ports of the '$COLLECTION' collection in the right order"
```

When I had read that previously I thought it will list them in the right order according to dependencies

Looking at the code it seems you only sort them.

```
list_ports() {
	cd $PORT_BASE && find . -name Pkgfile -follow -printf "%h\n" | sed 's|^./||g' | sort
}
```

So maybe it would be better to write:

```
will list all the ports of the '$COLLECTION' collection in alphabetical order"
```

**Comment by tnut** [comment]
will be list by alphabetic and level order actually
