### ISSUE TITLE
[xfce 4]Le greffon météo ne détecte pas mon emplacement géographique.

### ISSUE THREAD

**Issue by FredBezies** [NuTyX/xfce4#7]
Simple à reproduire. Dans un xfce fraichement installé, il suffit de rajouter le greffon météo, puis d'aller dans propriétés. Je suis parti de la NuTyX 8.2rc2.

Ce dernier ne trouve pas l'emplacement. Obligé de le définir manuellement.

![meteo xfce4](https://cloud.githubusercontent.com/assets/8571419/18866226/4b124f24-849f-11e6-8f92-46c8113ce21a.png)

**Comment by tnut** [comment]
wont fix
